apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: luxe-aws-secrets
  namespace: luxe-app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "luxe-app-config"
        objectType: "secretsmanager"