apiVersion: v1
kind: Service
metadata:
  name: luxe-app-service
  namespace: luxe-app
spec:
  selector:
    app: luxe-app
  ports:
    - protocol: TCP
      port: 80        # Port exposed internally
      targetPort: 80  # Port your container listens on (Match deployment.yaml)
  type: NodePort      # Required for ALB Ingress