apiVersion: v1
kind: ServiceAccount
metadata:
  name: default 
  namespace: luxe-app
  annotations:
    # IMPORTANT: After 'terraform apply', you must replace this ARN 
    # with the real one from your AWS Console or Terraform Output.
    eks.amazonaws.com/role-arn: "arn:aws:iam::349020400385:role/luxe-app-sa-role"